# Generated by Django 5.0.4 on 2024-05-01 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('year', models.CharField(max_length=4)),
            ],
            options={
                'db_table': 'funding',
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('year_published', models.CharField(max_length=4)),
            ],
            options={
                'db_table': 'publication',
            },
        ),
        migrations.CreateModel(
            name='Teaches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
            options={
                'db_table': 'teaches',
            },
        ),
        migrations.RemoveField(
            model_name='prereq',
            name='course',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.AlterModelOptions(
            name='course',
            options={},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={},
        ),
        migrations.AlterModelOptions(
            name='instructor',
            options={},
        ),
        migrations.AddField(
            model_name='funding',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.instructor'),
        ),
        migrations.AddField(
            model_name='publication',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.instructor'),
        ),
        migrations.AddField(
            model_name='teaches',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.course'),
        ),
        migrations.AddField(
            model_name='teaches',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.instructor'),
        ),
        migrations.AddField(
            model_name='teaches',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.section'),
        ),
        migrations.DeleteModel(
            name='Prereq',
        ),
        migrations.AlterUniqueTogether(
            name='teaches',
            unique_together={('course', 'section', 'semester', 'year', 'instructor')},
        ),
    ]
