# Generated by Django 5.0.4 on 2024-05-01 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_funding_publication_teaches_remove_prereq_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='department',
            name='building',
        ),
        migrations.RemoveField(
            model_name='department',
            name='dept_name',
        ),
        migrations.AddField(
            model_name='course',
            name='dept_name',
            field=models.CharField(default='Default Department', max_length=50),
        ),
        migrations.AddField(
            model_name='department',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instructor',
            name='dept_name',
            field=models.ForeignKey(blank=True, db_column='dept_name', default=1, on_delete=django.db.models.deletion.CASCADE, to='admins.department'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='credits',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
